{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "f28c3796-003d-42d7-a844-ef9bfb4ea66a",
   "metadata": {},
   "source": [
    "Este script carrega o conjunto de dados bruto, realiza a limpeza, a codificação das variáveis categóricas, a divisão de treino/teste com estratificação e salva os dados em data/processed/."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "bbbcd210-d889-47d8-8ec6-bfd212d8185e",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import pandas as pd\n",
    "from sklearn.model_selection import train_test_split\n",
    "\n",
    "\n",
    "def preprocess_data(\n",
    "    data_path=\"../telco_customer_churn.xlsx\", output_dir=\"../data/processed\"\n",
    "):\n",
    "    print(\"[ETL] Carregando dados brutos...\")\n",
    "    df = pd.read_excel(data_path, sheet_name=0)\n",
    "\n",
    "    df_clean = df.copy()\n",
    "\n",
    "    # 1. Remoção de identificadores\n",
    "    if \"customerID\" in df_clean.columns:\n",
    "        df_clean = df_clean.drop(columns=[\"customerID\"])\n",
    "\n",
    "    # 2. Mapeamento de variáveis binárias\n",
    "    if \"gender\" in df_clean.columns:\n",
    "        df_clean[\"gender\"] = df_clean[\"gender\"].map({\"Male\": 1, \"Female\": 0})\n",
    "\n",
    "    binarias = [\"Partner\", \"Dependents\", \"PhoneService\", \"PaperlessBilling\"]\n",
    "    for col in binarias:\n",
    "        if col in df_clean.columns:\n",
    "            df_clean[col] = df_clean[col].map({\"Yes\": 1, \"No\": 0})\n",
    "\n",
    "    if \"Churn\" in df_clean.columns:\n",
    "        df_clean[\"Churn\"] = df_clean[\"Churn\"].map({\"Yes\": 1, \"No\": 0})\n",
    "\n",
    "    # 3. One-Hot Encoding para categóricas\n",
    "    colunas_multicategoria = [\n",
    "        \"MultipleLines\",\n",
    "        \"InternetService\",\n",
    "        \"OnlineSecurity\",\n",
    "        \"OnlineBackup\",\n",
    "        \"DeviceProtection\",\n",
    "        \"TechSupport\",\n",
    "        \"StreamingTV\",\n",
    "        \"StreamingMovies\",\n",
    "        \"Contract\",\n",
    "        \"PaymentMethod\",\n",
    "    ]\n",
    "\n",
    "    df_prep = pd.get_dummies(\n",
    "        df_clean,\n",
    "        columns=colunas_multicategoria,\n",
    "        drop_first=True,\n",
    "        dtype=int,\n",
    "    )\n",
    "\n",
    "    X = df_prep.drop(columns=[\"Churn\"])\n",
    "    y = df_prep[\"Churn\"]\n",
    "\n",
    "    # 4. Divisão de treino e teste estratificada\n",
    "    X_train, X_test, y_train, y_test = train_test_split(\n",
    "        X, y, test_size=0.2, random_state=42, stratify=y\n",
    "    )\n",
    "\n",
    "    # 5. Persistência dos conjuntos de dados\n",
    "    os.makedirs(output_dir, exist_ok=True)\n",
    "    X_train.to_csv(os.path.join(output_dir, \"X_train.csv\"), index=False)\n",
    "    X_test.to_csv(os.path.join(output_dir, \"X_test.csv\"), index=False)\n",
    "    y_train.to_csv(os.path.join(output_dir, \"y_train.csv\"), index=False)\n",
    "    y_test.to_csv(os.path.join(output_dir, \"y_test.csv\"), index=False)\n",
    "\n",
    "    print(\n",
    "        f\"[ETL] Dados processados e salvos com sucesso na pasta '{output_dir}'!\"\n",
    "    )\n",
    "\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    preprocess_data()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
